### ISSUE TITLE
Cant "edit" "media item" in "library"

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#486] opened 2022-12-13 06:26 UTC
Adding my first dummy item to media library.
Chose to try to replicate this page in Drupal: https://westernfriend.org/media/wf-podcast-seventeen-frank-granshaw-science-justice
Uploaded the "soundbite" and then saw that the image renders way too big.
Clicked on "edit this media item" and got a long error message.

**Comment by brylie** [comment] 2022-12-14 17:15
I can't reproduce this error locally. Can you post a screenshot of the error message or the exact error text so that I can troubleshoot this further?

**Comment by marycklein** [comment] 2022-12-20 05:19
![Cant-edit-media_2022-12-19](https://user-images.githubusercontent.com/44241543/208589543-16190429-15d2-46e5-baff-6feac2c508a7.jpg)

**Comment by brylie** [comment] 2022-12-20 05:46
Thanks for providing the steps to reproduce this bug.

It looks like this is a known bug with the Wagtail Media plugin, which should be fixed soon if it isn't already:

https://github.com/torchbox/wagtailmedia/issues/180

**Comment by marycklein** [comment] 2022-12-20 05:48
Yippee!!

The footer looks GREAT!!

I am putting together an image of “tweaks” to spacing, but I believe these are minor.

Then I will be off to other tasks for the evening.

:-)
m


Mary Klein
Editor / Executive Director

Western Friend
2625 Middlefield Road, #565
Palo Alto, CA  94306-2516
650-318-1652

**Closed** 2022-12-20 05:56 UTC
Labels: bug
