### ISSUE TITLE
Library - Page-turning widget

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#867] opened 2023-09-13 05:11 UTC
Page-turning widget does not seem to be functioning properly. “First” does not take back to page “1”

**Comment by matejtuke** [comment] 2023-09-26 16:57
Is tis still a issue? How can I test it .. maybe interested in solving the problem

**Comment by brylie** [comment] 2023-09-26 17:14
It still remains open. You can test the bug to see if it can be reproduced by visiting any issue in our Deep Archive and clicking on the table of contents items within that issue: https://staging.westernfriend.org/magazine/deep-archive/

**Comment by matejtuke** [comment] 2023-09-26 17:54
It seems to be working for me. Th problem I see is the footer element which is hiding bottom of the widget, where I can turn the pages by arrows

**Comment by matejtuke** [comment] 2023-09-27 06:38
![image](https://github.com/WesternFriend/WF-website/assets/146000059/7b90880d-fc3c-4faa-a658-a6e664fc49a3)

**Comment by brylie** [comment] 2023-09-27 16:10
Thanks @matejtuke. I've opened issue #892 to fix the table of contents/footer overlap. Would you like to investigate #892 for now?

**Comment by matejtuke** [comment] 2023-09-27 17:23
yes, I am going to comment on that issue and please assign that to me.

**Comment by brylie** [comment] 2023-11-19 14:28
Closing since this was resolved

**Closed by brylie** 2023-11-19 14:28 UTC
